# Generated by Django 6.1 on 2026-10-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
